import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import PrelineScript from "@/components/PrelineComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`${inter.className} md:mx-auto mx-4 md:px-16 md:max-w-[80%] bg-white`}
      >
        <Navbar />
        {children}
      </body>
      <PrelineScript />
    </html>
  );
}
